function genmagstr(obj, varargin)
% generates magnetic structure
%
% GENMAGSTR(obj, 'option1', value1 ...)
%
% There are several ways to generate magnetic structure. The selected
% method depends on the 'mode' option, see below. The magnetic structure is
% stored in the obj.mag_str field. The default mode is 'extend'. The
% magetic structure is stored as Fourier components with arbitrary number
% of wave vectors in the spinw object. However spin waves can be only
% calculated if the magnetic structure has only a single propagation vector
% (plus a k=0 ferromagnetic component) we simply call it single-k magnetic
% structure. Thus genmagstr() enables to input magnetic structures that
% comply with this restriction by defining a magnetic structure by the
% moment directions (S) in the crystallographic cell, a propagation vector
% (km) and a vector that defines the normal of the rotation of the spin
% spiral (n). The function converts these values into Fourier components to
% store. To solve spin wave dispersion of magnetic structures with multiple
% propagation vectors, a magnetic supercell has to be defined where the
% propagation vector can be approximated to zero.
%
% Input:
%
% obj       spinw class object.
%
% Options:
%
% mode       Mode how the magnetic structure is generated:
%
%            'random'
%                   generates random zero-k magnetic structure.
%
%            'direct'
%                   direct input of the magnetic structure using the 
%                   parameters of the single-k magnetic structure.
%
%            'extend' (default)
%                   Simply extends the existing or input structure
%                   (param.S) into a magnetic supercell by replicating it.
%                   If no structure is stored in the spinw object a random
%                   structure is generated automatically. If defined,
%                   param.S is used as starting structure for extension
%                   overwriting the stored structure. If the original
%                   structure is already extended with other size, only the
%                   moments in the crystallographic cell wil be replicated.
%                   Magnetic ordering wavevector k will be set to zero. To
%                   generate structure with non-zero k, use 'helical' or
%                   'direct' option.
%
%            'helical'
%                   generates helical structure in a single cell or in a
%                   supercell. In contrary to the 'extend' option the
%                   magnetic structure is not generated by replication but
%                   by rotation of the moments using the following formula:
%
%                       S_gen_i(r) = ROT(2*pi*km*r)*S_i.
%
%                   where S_i has either a single moment or as many moments
%                   as the number of magnetic atoms in the crystallographic
%                   cell. In the first case 'r' denotes the atomic
%                   positions, while for the second case 'r' denotes the
%                   position of the origin of the cell.
%
%            'rotate'
%                   uniform rotation of all magnetic moments with a
%                   param.phi angle around the param.n vector. If
%                   param.phi=0, all moments are rotated so, that the first
%                   moment is parallel to param.n vector in case of
%                   collinear structure or in case of planar structure
%                   param.n defines the normal of the plane of the magnetic
%                   moments.
%
%            'func'
%                   function that defines the parameters of the single-k
%                   magnetic structure: moment vectors, propagation vector
%                   and normal vector from arbitrary parameters in the
%                   following form:
%
%                       [S, k, n] = @(x)func(S0, x)
%
%                   where S is matrix with dimensions of [3 nMagExt]. k is
%                   the propagation vector, its dimension is [1 3]. n is
%                   the normal vector of the spin rotation plane, its
%                   dimension is [1 3]. The default function is
%                   @gm_spherical3d. For planar magnetic structure use
%                   @gm_planar. Only param.func and param.x have to be
%                   defined for this mode.
%
%            'fourier'
%                   store general magnetic structure by the given Fourier
%                   components. The moments for a magnetic supercellare
%                   defined using the following equation:
%
%                       F(l,j,k) = F(j,k)*exp(-i*k*l)
%
%                   Where F(l,j,k) is the generated k-Fourier component on
%                   the l-th unit cell, j-th atom. The size of the
%                   generated supercell is determined by the 'nExt' option.
%                   The 'Fk' option gives the Furier components and the
%                   k-vectors in a cell in the following structure: {Fk1 k1
%                   Fk2 k2 ...} The Fk1, Fk2 etc are complex matrices that
%                   contain the Fourier compoents on every magnetic atom in
%                   the crystallographic cell. They have a dimension of [3
%                   nMagAtom]. The k1, k2 etc are k-vectors of the Fourier
%                   componets, with dimensions of [1 3]. Since the
%                   generated magnetic structures have to be real, the -k
%                   componets are automatically added: F(-k) = conj(F(k)).
%                   Example input: {[1 -1;i1 -i1;0 0] [1/2 0 0] [1 -1;0 0;
%                   i1 -i1] [0 1/2 0]} This gives a double k structure for
%                   a lattice with two magnetic atoms in the unit cell. The
%                   Fourier componets are by default in the xyz coordinate
%                   system but if param.unitS is set to 'lu', than the
%                   moment components are assumed to be in lattice units.
%
% phi       Angle of rotation of the magnetic moments in rad. Default
%           value is 0.
% phid      Angle of rotation of the magnetic moments in degree. Default
%           value is 0.
% nExt      Size of the magnetic supercell in multiples of the
%           crystallographic cell, dimensions are [1 3]. Default value is
%           stored in obj. If nExt is a single number, then the size of the
%           extended unit cell is automatically determined from the
%           magnetic ordering wavevector. If nExt = 0.01, then the number
%           of unit cells is determined so, that in the extended unit cell,
%           the magnetic ordering wave vector is [0 0 0], within the given
%           0.01 error.
% k         Magnetic ordering wavevector in r.l.u., dimensions are [1 3].
%           Default value is defined in obj.
% n         Normal vector to the spin rotation plane for single-k magnetic
%           structures, dimensions are [1 3]. Default value [0 0 1].
% S         Direct input of the spin values, dimensions are [3 nSpin].
%           Every column defines the three (S_x, S_y, S_z) components of
%           the moment in the xyz Descartes coodinate system or in l.u.
%           coordinate system. Default value is stored in obj.
% Fk        Fourier compoents for general magnetic structures.
%           For description, see the 'fourier' mode description above.
%           No default value, it has to be defined if 'mode' is 'fourier'.
% unitS     Units for S and Fk, default is 'xyz', optionally 'lu' can be used,
%           in this case the input spin components are assumed to be in
%           lattice units and they will be converted to the xyz coordinate
%           system. Lattice units are determined by components along the
%           three lattice vector (length normalized to unity).
% epsilon   The smalles value of incommensurability that is
%           tolerated without warning in lattice units. Default is 1e-5.
% func      Function that produce the magnetic moments, ordering wave
%           vector and normal vector from the param.x parameters in the
%           following form:
%
%             [M, k, n] = @(x)func(M0,x)
%
%           where M is (3,nMagExt) size matrix, k is the propagation vector
%           with dimensions of [1 3], n is the normal vector of the spin
%           rotation plane, its dimensions are [1 3]. The default function
%           is @gm_spherical3d. For planar magnetic structure use
%           @gm_planar.
% x0        Input parameters for param.func function, dimensions are
%           [1 nx].
% norm      Set the length of the generated magnetic moments to be equal to
%           the spin of the magnetic atoms. Default is true.
% r0        If true and only a single spin direction is given, the spin
%           phases are determined by atomic position times k-vector, while
%           if it is false, the first spin will have zero phase. Default is
%           true.
%
% Output:
%
% The obj.mag_str field will contain the new magnetic structure using
% Fourier components.
%
% Example:
%
% USb = spinw;
% USb.genlattice('lat_const',[6.203 6.203 6.203],'angled',[90 90 90],'spgr','F m -3 m')
% USb.addatom('r',[0 0 0],'S',1)
% FQ = {[0;0;1+1i] [0 0 1] [0;1+1i;0] [0 1 0] [1+1i;0;0] [1 0 0]};
% USb.genmagstr('mode','fourier','Fk',FQ,'nExt',[1 1 1])
% plot(USb,'range',[1 1 1])
%
% The above example creates the multi-q magnetic structure of USb with the
% FQ Fourier components and plots the magnetic structure.
%
% See also SPINW, SPINW.ANNEAL, SPINW.OPTMAGSTR, GM_SPHERICAL3D, GM_PLANAR.
%

if isempty(obj.matom.r)
    error('spinw:genmagstr:NoMagAtom','There are no magnetic atoms (S>0) in the unit cell!')
end

inpForm.fname  = {'mode'   'nExt'            'k'           'n'    };
inpForm.defval = {'extend' obj.mag_str.nExt obj.mag_str.k  [0 0 1]};
inpForm.size   = {[1 -1]   [1 -4]            [1 3]         [1 3]  };
inpForm.soft   = {false    false             false         false  };

inpForm.fname  = [inpForm.fname  {'func'          'x0'   'norm' 'r0' }];
inpForm.defval = [inpForm.defval {@gm_spherical3d []     true   true }];
inpForm.size   = [inpForm.size   {[1 1]           [1 -3] [1 1]  [1 1]}];
inpForm.soft   = [inpForm.soft   {false           true   false  false}];

inpForm.fname  = [inpForm.fname  {'S'     'phi' 'phid' 'epsilon' 'unitS' 'Fk'      }];
inpForm.defval = [inpForm.defval {[]      0     0      1e-5      'xyz'   cell(1,0) }];
inpForm.size   = [inpForm.size   {[-6 -2] [1 1] [1 1]  [1 1]     [1 -5]  [1 -7]    }];
inpForm.soft   = [inpForm.soft   {true    false false  false     false   false     }];

param = sw_readparam(inpForm, varargin{:});

if param.phi == 0
    % use degrees for phi is given
    param.phi = param.phid*pi/180;
end

% make string lower case
param.mode = lower(param.mode);

if isempty(param.S)
    param.S = obj.magstr.S;
else
    % number of rows in .S has to be three
    if numel(param.S) == 3
        param.S = param.S(:);
    elseif (size(param.S,1) ~= 3)
        error('spinw:genmagstr:WrongInput','Parameter S has to have dimensions of [3 nSpin]!');
    end
    
    switch lower(param.unitS)
        case 'lu'
            % convert the moments from lattice units to xyz
            BV = obj.basisvector(true);
            param.S = BV*param.S;
            
            % convert also the Fourier components if they are given
            if ~isempty(param.Fk)
                for ii = 1:2:numel(param.Fk)
                    param.Fk{ii} = BV*param.Fk{ii};
                end
            end
        case 'xyz'
            % do nothing
        otherwise
            error('spinw:genmagstr:WrongInput','Parameter unitS has to be either ''xyz'' or ''lu''!');
    end
end

nExt     = double(param.nExt);

% automatic determination of the size of the extended unit cell
% if nExt is a single number
if numel(nExt) == 1
    [~, nExt] = rat(param.k,nExt);
end

mAtom    = obj.matom;
nMagAtom = size(mAtom.r,2);
nMagExt  = nMagAtom*prod(nExt);

if nMagAtom==0
    error('sw:genmagstr:NoMagAtom','There is no magnetic atom in the unit cell with S>0!');
end

% Create mAtom.Sext matrix.
mAtom    = sw_extendlattice(nExt, mAtom);

% Magnetic ordering wavevector
k = param.k;

% Axis of rotation, size (1,3)
n = (param.n)/norm(param.n);

% If the magnetic structure is not initialized start with a random one.
if strcmp(param.mode,'extend') && (nMagAtom > size(param.S,2))
    param.mode = 'random';
    % this warning is not necessary
    %warning('sw:genmagstr:WrongInitialStructure','No magnetic structure is defined, random structure is created instead!')
end

if obj.symb
    k = sym(k);
    param.S = sym(param.S);
    n = sym(n);
end

switch param.mode
    case 'extend'
        % Extend the unit cell if:
        % -the new number of extended cells does not equal to the number of
        %  cells defined in obj
        % -the number of spins stored in obj is not equal to the number
        %  of spins in the final structure
        if any(obj.mag_str.N_ext - int32(param.nExt)) || (size(param.S,2) ~= nMagExt)
            S = param.S(:,1:nMagAtom);
            S = repmat(S,[1 prod(nExt)]);
        else
            S = param.S;
        end
        k = [0 0 0];
    case 'random'
        % Create random spin directions.
        S = randn(nMagExt,3);
        S = bsxfun(@rdivide,S,sqrt(sum(S.^2,2)));
        S = bsxfunsym(@times,S,mAtom.Sext')';
        k = [0 0 0];
    case 'helical'
        S0 = param.S;
        % Magnetic ordering wavevector in the extended unit cell.
        kExt = k.*nExt;
        % Warns about the non sufficient extension of the unit cell.
        % we substitute random values for symbolic km
        skExt = sw_sub1(kExt,'rand');
        if any(abs(skExt-round(skExt))>param.epsilon) && prod(nExt) > 1
            warning('sw:genmagstr:UCExtNonSuff','In the extended unit cell k is still larger than epsilon!');
        end
        % Number of spins in the input.
        nSpin = size(param.S,2);
        
        if (nSpin~= nMagAtom) && (nSpin==1)
            % Single defined spin, use the atomic position.
            if param.r0
                r = mAtom.RRext;
            else
                r = bsxfun(@minus,mAtom.RRext,mAtom.RRext(:,1));
            end
        elseif nSpin == nMagAtom
            % First crystallographic unit cell defined, use only unit cell
            % position.
            r = bsxfun(@rdivide,floor(bsxfun(@times,mAtom.RRext,nExt')),nExt');
        else
            error('sw:genmagstr:WrongNumberSpin','Wrong number of input spins!');
        end
        % Angles of rotation for each unit cell.
        phi = kExt*r*2*pi;
        
        % Spin in the extended unit cell.
        S = zeros(3,nMagExt);
        if obj.symbolic
            S = sym(S);
        end
        
        if isreal(param.S) || isa(param.S,'sym')
            % Rotate spins for each unit cell.
            for ii = 1:nMagExt
                selS    = S0(:,mod(ii-1,nSpin)+1);
                S(:,ii) = sw_rot(n,phi(ii),selS);
            end
        else
            error('sw:genmagstr:WrongInput','For complex Fourier components use the ''mode'' ''fourier'' option!');
        end
    case 'direct'
        % Direct input of the magnetic moments.
        S = param.S;
        if size(S,2)==nMagAtom
            % single unit cell
            nExt = [1 1 1];
        end
        
        if (size(S,1) ~= 3) || (size(S,2) ~= nMagExt)
            error('sw:genmagstr:WrongSpinSize','Wrong size of param.S!');
        end
    case 'rotate'
        S   = param.S;
        if param.phi == 0
            % The starting vector, size (1,3):
            S1 = sw_nvect(S);
            % Axis of rotation defined by the spin direction
            nRot  = cross(n,S1);
            % Angle of rotation.
            phi = -atan2(norm(cross(S1,n)),dot(S1,n));
        else
            nRot = n;
            % Angle of rotation.
            phi = param.phi(1);
        end
        % Rotate the spins.
        S = sw_rot(nRot,phi,S);
        n = obj.mag_str.n;
        k = obj.mag_str.k;
    case 'func'
        S = mAtom.S;
        S = repmat(S,[prod(nExt) 1]);
        
        if obj.symbolic
            [S, k, n] = param.func(sym(S), sym(param.x0));
        else
            [S, k, n] = param.func(S,param.x0);
        end
    case 'fourier'
        % generate supercell from Fourier components
        % keeps the final k-vector zero
        Fk = param.Fk;
        if isempty(Fk) || ~iscell(Fk)
            error('spinw:genmagstr:WrongInput','Wrong ''Fk'' option that defines the Fourier components!');
        end
        
        % number of moments for the Fourier components are defined
        nFourier = size(Fk{1},2);
        nQ = numel(Fk)/2;
        
        if (nFourier ~= nMagAtom) && (nFourier==1)
            % Single defined moment, use the atomic position in l.u.
            RR = bsxfun(@times,mAtom.RRext,nExt');
        elseif nFourier == nMagAtom
            % First crystallographic unit cell defined, use only unit cell
            % position in l.u.
            RR = floor(bsxfun(@times,mAtom.RRext,nExt'));
        else
            error('sw:genmagstr:WrongNumberComponent','Wrong number of input Fourier components!');
        end
        
        % no moments
        S = RR*0;
        % number of cells in the supercell
        nCell = prod(nExt);
        
        % save the Fourier components
        S = cat(3,Fk{1:2:end});
        k = cat(1,Fk{2:2:end})';
        
        % multiply the Fourier components with the spin quantum number
        % TODO
        
        
%         for ii = 1:2:(2*nQ)
%             % F(k)
%             S = S + bsxfunsym(@times,repmat(Fk{ii},[1 nCell*nMagAtom/nFourier]),exp(1i*Fk{ii+1}*RR*2*pi))/2;
%             % conj(F(k))
%             S = S + bsxfunsym(@times,repmat(conj(Fk{ii}),[1 nCell*nMagAtom/nFourier]),exp(-1i*Fk{ii+1}*RR*2*pi))/2;
%             
%         end
%         S = real(S);
% 
%         k = [0 0 0];
%         
        warning('spinw:genmagstr:Approximation',['The generated magnetic '...
            'structure is only an approximation of the input multi-q'...
            ' structure on a supercell!'])
        %n = [0 0 1];
        
    otherwise
        error('spinw:genmagstr:WrongMode','Wrong param.mode value!');
end

% normalize the magnetic moments
% if param.norm
%     normS = sqrt(sum(S.^2,1))./repmat(mAtom.S,[1 prod(nExt)]);
%     normS(normS==0) = 1;
%     S = bsxfunsym(@rdivide,S,normS);
%     %if any(isnan(S(:)))
%     %    error('spinw:genmagstr:WrongMoments','Zero magnetic moments cannot be normalized!');
%     %end
%     
% end

% simplify expressions
if obj.symbolic
    S = simplify(sym(S));
    k = simplify(sym(k));
    n = simplify(sym(n));
end

mag_str.nExt = int32(nExt(:))';
mag_str.k    = k;
mag_str.S    = S;

obj.mag_str   = mag_str;
validate(obj);

end